name: news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_native_splash: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/app_bg.webp
    - assets/google.png
    - assets/facebook.png
    - assets/app_logo.png

flutter_native_splash:
  image: "assets/app_logo.png"
  color: "ffffff"
